### ISSUE TITLE
Color Discrepancy

### ISSUE THREAD

**Issue by mjsadaway** [CQCumbers/kle_render#10]
Rendered keycap colors vary significantly from those specified in KLE and are apparently incorrect.

In the KLE layout (first image), the specified keycap colors are #1a8ab7 (BFN) and #0073a2 (BFP). These values match both the Signature Plastics ABS color swatches (third image) and the sides of the keycaps as sampled by Photoshop. KLE is known to use possibly incorrectly lightened color values for the tops of the keycaps, which is of course one of the reasons KLE-Render is used.

The "Case Background" specified in KLE is also #1a8ab7 (BFN). Sampling the background color yields this value.

However, it is visually obvious that the colors used by KLE-Render (second image) don't match the specified colors. As expected due to lighting effects, sampling the keycap colors yields multiple values, but none of these appear close to those originally specified. Sampling the rendered background color yields #4B88B5.

![layout](https://user-images.githubusercontent.com/42558043/94981993-0f9f3700-0505-11eb-9d0f-7f03a14820b0.png)
![render](https://user-images.githubusercontent.com/42558043/94982002-26458e00-0505-11eb-961e-a81fccb21f83.png)
![swatches](https://user-images.githubusercontent.com/42558043/94982004-28a7e800-0505-11eb-954a-967baa2b8df6.png)

**Comment by CQCumbers** [comment]
Hmm, that result is surprising. I've tried to replicate your layout with the colors you specified, and gotten a kle-render result pretty close in color to the keyboard-layout-editor PNG. The keys are a touch cooler (it is expected for lighting to affect hue as well as brightness) but the background colors match exactly. On the other hand, while my render matches your middle image well, my keyboard-layout-editor PNG looks very different from your top image, which is definitely too turquoise compared to the real plastic.

I've attached the image I rendered, though I'm not sure if it will show up differently on your computer. Is suspect the discrepancy could be due to a difference in color spaces somewhere along the display chain.

![comparison](https://user-images.githubusercontent.com/13649193/94993380-a64c1200-055e-11eb-8af8-9ce0749ae1d8.png)

**Comment by mjsadaway** [comment]
Thanks, CQ, for your reply.

The web browser in which KLE-Render is run appears to make a difference.

The top image, captured via Print Screen, shows the results for the original layout as displayed by Firefox (version 81.0.1) on the left and Chrome (version 85.0.4183.121) on the right.

The bottom image shows similar results for a second layout. The colors specified in KLE for the second layout are #5dcde3 (Signature Plastics PBT color BFV) and #34a4b9 (BFW).

In both cases, the colors displayed by Chrome are significantly different than those displayed by Firefox.

When the Chrome images are saved as PNGs and displayed with software other than Chrome, they match the Firefox images.

So it looks as though Chrome is displaying the colors incorrectly or at least differently from everyone else.

I don't recall doing so specifically, but I apparently captured the originally reported mismatching KLE-Render output using Chrome and Print Screen.

I guess this means KLE-Render is in the clear.

What's more clear is that any software on any computer will never display colors that precisely match actual plastic keycaps, To know how your keycaps will actually look, you need to obtain actual plastic samples and examine them under various lighting conditions. Then you need to hope that the batches of resin used to make your keycaps are close to the colors of the batches used to make your plastic samples.

Hopefully KLE and KLE-Render display colors accurately enough to enable you to at least narrow down color choices.

![Firefox (left) vs  Chrome (right) #1](https://user-images.githubusercontent.com/42558043/94999672-ff30a000-0588-11eb-8f80-f90064570c31.png)
![Firefox (left) vs  Chrome (right) #2](https://user-images.githubusercontent.com/42558043/94999681-0bb4f880-0589-11eb-9b97-e5528735b6b3.png)

**Comment by iandoug** [comment]
@mjsadaway

Can you compare the downloaded PNG (NOT via printscreen... use download button at top right) to the renders?

That creates an image directly from the canvas.

cheers, Ian

**Comment by iandoug** [comment]
> What's more clear is that any software on any computer will never display colors that precisely match actual plastic keycaps, To know how your keycaps will actually look, you need to obtain actual plastic samples and examine them under various lighting conditions. Then you need to hope that the batches of resin used to make your keycaps are close to the colors of the batches used to make your plastic samples.

A lot also depends on your monitor. Hopefully you didn't do print-screens while in some sort of 'night time' anti-blue-light mode.

> 
> Hopefully KLE and KLE-Render display colors accurately enough to enable you to at least narrow down color choices.
> 
> ![Firefox (left) vs Chrome (right) #1](https://user-images.githubusercontent.com/42558043/94999672-ff30a000-0588-11eb-8f80-f90064570c31.png)
> ![Firefox (left) vs Chrome (right) #2](https://user-images.githubusercontent.com/42558043/94999681-0bb4f880-0589-11eb-9b97-e5528735b6b3.png)

**Comment by mjsadaway** [comment]
Thanks, Ian, for your ideas. As explained below, I've discovered the problems occur on only one of two computers, so KLE and KLE-Render are apparently not at fault. I'm including my TL;DR notes here in case they might be of use to another user with similar problems.

> Can you compare the downloaded PNG (NOT via printscreen... use download button at top right) to the renders?

KLE's "Download PNG" function was used to capture the layout shown is the first image in my first post, and KLE was run from Firefox. When I run KLE from Chrome and use the "Download PNG" function, I (not unexpectedly) get an identical PNG file.

When I save the images produced by KLE-Render running on either Firefox or Chrome as PNGs, both KLE-Render images match both KLE images visually, and all four images have the same background color when sampled in Photoshop.

This indicates KLE-Render is working correctly, whether it is run from either Firefox or Chrome._

The problems are, at least when using the same computer that produced all of the previous images, that:

1. Both the KLE and KLE-Render images as displayed by Chrome are visually more blue than the same images as displayed by Firefox.

2. All four of the images when saved as PNGs are visually more turquoise than CQCumber's images of the same layout.

These problems are illustrated by the side-by-side Firefox-vs.-Chrome images posted previously.

HOWEVER, when I run the same tests using Firefox and Chrome on a second computer:

1. All four images match visually as displayed by Firefox and Chrome and when saved as PNGs.

2. All four images saved as PNGs have the correct background color as sampled by Photoshop.

3. All four images visually match CQCumbers's results.

In other words, the problems occur on only one of two computers.

> A lot also depends on your monitor. Hopefully you didn't do print-screens while in some sort of 'night time' anti-blue-light mode.

On the first computer, the one that exhibits the problems, the monitor itself is set to sRGB mode, the monitor's "low blue light" mode is turned off, Windows 10 is using the color profile supplied with the monitor, and Windows 10's "Night light" feature is turned off.

Also note that the side-by-side images from Firefox and Chrome were captured simultaneously via Print Screen and should therefore be equally affected by the hardware and software configuration.

RESULTS FROM THE SECOND COMPUTER

From top to bottom, saved as PNGs:

KLE image from Firefox
KLE-Render from Firefox
KLE image from Chrome
KLE-Render from Chrome

![Firefox KLE](https://user-images.githubusercontent.com/42558043/95006345-9c172b80-05d1-11eb-8e0b-308795e939d8.png)
![Firefox KLE-Render](https://user-images.githubusercontent.com/42558043/95006409-41ca9a80-05d2-11eb-9b99-a9e1df23b9f7.png)
![Chome KLE](https://user-images.githubusercontent.com/42558043/95006351-a89b8400-05d1-11eb-8b97-8697968d7906.png)
![Chrome KLE-Render](https://user-images.githubusercontent.com/42558043/95006352-af29fb80-05d1-11eb-8ead-20751154f699.png)

**Comment by mjsadaway** [comment]
The first computer was made to display the same colors in both Firefox and Chrome by changing a Chrome flag:

1. Type "chrome://flags" in Chrome's address bar.
2. Search for "Force color profile".
3. Change its value from "Default" to "sRGB".

This causes Chrome to display colors like Firefox and most other software instead of "correcting" them in whatever way it thinks is best.

If you then sample the colors of your KLE layout or KLE-Render background color with your favorite color picker tool, you will get the values you specified in KLE.

Whether this makes the displayed colors any more or less like the actual colors of the real keycaps is TBDL.

But at least it's consistent.

**Comment by iandoug** [comment]
> Whether this makes the displayed colors any more or less like the actual colors of the real keycaps is TBDL.

Ian Prest (author of KLE) bought a colourimeter to sample the colours of the keycaps. He then uses CSS to lighten the tops. I also noticed that my SP DSA keycaps did not look the same colour as what was rendered on screen. It may look the same on his monitor.

KLE-render is taking a completely different approach to rendering the colour.

It is actually very difficult to put the colour on screen ... objects are Reflected light, and screens are generated light.

GMK sent me their colour swatches and I tried to convert their colours to HTML colour codes, first by sticking them on the screen and trying to find the RGB values that matched. Only partially successful. So I took them outside in direct sunlight and took photos with my SLR, and tried to pick a colour from the images, but they were not one solid colour. So again, partially successful.

At that point I gave up and posted them off to Ian, he scanned them and added to KLE. Then I compared the colours he got to my 'best' ... some were close, some not.

Actually busy with similar process this weekend ... trying to add assorted acrylic etc colours as background. Am picking colours from websites and official PDFs ... website photos have same issue I had, the colour is not solid. Even two different PDFs from same company give different values in colour picker. They also warn colours are 'best they can do, given limitations of printing process' etc.

On top of that, different monitors display colours differently, so it's always going to be 'approximate'.

Cheers, Ian

**Comment by b4imetu** [comment]
- This is how #ffee00 looks like in `keyboard-layout-editor`
![keyboard-layout](https://user-images.githubusercontent.com/41535001/129442130-a4d2d77b-7179-4d93-af29-d89727423913.png)
- This is how #ffee00 looks like after `kle-render`
![download](https://user-images.githubusercontent.com/41535001/129442135-922a3db2-a8cf-47f2-aa67-264fcfa42f1c.png)

The differences between them are so huge that I really hope `kle-render` can show the original color correctly.

**Comment by CQCumbers** [comment]
There's practically always going to be differences in color appearance between different browsers, software, 3D renders, photos, and physical reality. If you want your colors to look a certain way in KLE-Render, you'll have to tweak them based on what you see in KLE-Render. In order to visually match keyboard-layout-editor's colors, you may need to use different color codes.

I would also advise against using very brightly saturated colors like `#ffee00` for keycaps you intend to manufacture, since the space of colors that a manufacturer can feasibly print or mix is almost certainly more limited than the color space your monitor displays when using keyboard-layout-editor.
