### ISSUE TITLE
The Heroku "Application error" is back

### ISSUE THREAD

**Issue by mjsadaway** [CQCumbers/kle_render#11]
https://kle-render.herokuapp.com/ hasn't been working for a few days.

I've used it hundreds of times recently. If there's a limit on usage, please let us know.

Meanwhile, I've been running it locally. See "Running KLE-Render locally on Windows 10".

Thanks.

**Comment by CQCumbers** [comment]
There's no limit on usage, but the server can crash, perhaps due to running out of memory or bugs in the program. Unfortunately I do not have enough logs stored to diagnose the issue in this case. It should be back online now though.
