### ISSUE TITLE
Running KLE-Render locally on Windows 10

### ISSUE THREAD

**Issue by mjsadaway** [CQCumbers/kle_render#12]
I'm not a Python user, and it took several tries to get this to work, so I'm not sure the following is correct if you're starting from scratch and not depending on leftovers from previous attempts. Any corrections would be appreciated.

To run KLE-Render locally on your Windows 10 system rather than online:

1. Download the KLE-Render code from https://github.com/CQCumbers/kle_render/archive/master.zip.
2. Unzip this file and note the location of the kle_render-master folder.
3. Download Python 3.8 from https://www.python.org/ftp/python/3.8.6/python-3.8.6-amd64.exe and install.. 
4. From a Windows command prompt run as Administrator:
    a. Install pipenv by entering "pip install pipenv".
    b. Navigate to the location of the kle_render-master folder by entering something like "cd C:\Users\Administrator\Desktop\KEYBOARDS\SOFTWARE\kle_render-master".
    c. Install KLE-Render by entering "pipenv install".
    d. Ignore the error message "ERROR: Couldn't install package: pillow-simd" if you get it.
    e. Run KLE-Render by entering "pipenv run python app.py".
    f. Note the web address in the message "Running on http://127.0.0.1:5000/".
5. From your favorite web browser, go to the web address noted.

Please let me know if you try this and find that it works or doesn't.

Thanks.

**Comment by DanielGGordon** [comment]
Followed steps and ended up with the following output after step `e`:

```
C:\Users\dgord\Desktop\OhKeycaps\kle-render\kle_render-master>pipenv run python app.py
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from keyboard import Keyboard
  File "C:\Users\dgord\Desktop\OhKeycaps\kle-render\kle_render-master\keyboard.py", line 2, in <module>
    from PIL import Image, ImageColor, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
```

**Comment by CQCumbers** [comment]
I believe the steps here are correct with the exception of `d`. You should not ignore the error messages as Pillow does in fact need to be installed for KLE-Render to work locally.
