### ISSUE TITLE
Spaces omitted from legends like "Caps Lock"

### ISSUE THREAD

**Issue by mjsadaway** [CQCumbers/kle_render#13]
![KLE Caps Lock](https://user-images.githubusercontent.com/42558043/95722420-e9367580-0c41-11eb-8f0c-63074255cd8e.png) is rendered as ![KLE-Render Caps Lock](https://user-images.githubusercontent.com/42558043/95722425-eb98cf80-0c41-11eb-8b7b-0fee20fc4422.png).
 
This also makes it impossible to get a good representation of the popular format in which both legends on the digit and punctuation keys are placed in the top half of the keycap.

![KLE Number Row](https://user-images.githubusercontent.com/42558043/95723627-572f6c80-0c43-11eb-8dd2-884d79eb0ecd.png) is rendered as 
![KLE-Render Number Row](https://user-images.githubusercontent.com/42558043/95724039-dae95900-0c43-11eb-882d-439d0e9d14bb.png), which doesn't look great without the spaces.

**Comment by CQCumbers** [comment]
This should be fixed by 08ae013, which corrects the width of the space glyph in the GMK font.
