### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by iandoug** [CQCumbers/kle_render#2]
hi

Um, how do I save the generated image? RIght-click->Save as doesn't work...
Unless it's a browser issue.

thanks, Ian

**Comment by CQCumbers** [comment]
Image saving works for me, and I haven't heard of problems saving the generated image from any other users. I am fairly certain this is a browser issue.

**Comment by iandoug** [comment]
Can confirm that file->save as on the generated image works now. Thanks.
