### ISSUE TITLE
Long layouts truncated?

### ISSUE THREAD

**Issue by iandoug** [CQCumbers/kle_render#3]
Hi
Playing around.
Need to generate long layout (19 keys wide).
Seems to get cut off.

![spectacle x18350](https://user-images.githubusercontent.com/12673886/32148124-b66fc190-bcfa-11e7-87d1-92dbb5fd2e98.png)

**Comment by CQCumbers** [comment]
I added canvas expansion in https://github.com/CQCumbers/kle_render/commit/5239933447ee3d5718fdfc12aefe756031c663c6. Narrow layouts should no longer be truncated.

**Comment by iandoug** [comment]
Confirmed working, thanks... :-)
