### ISSUE TITLE
how to make it work

### ISSUE THREAD

**Issue by iandoug** [CQCumbers/kle_render#9]
Hi

Can you maybe point me somewhere that shows how to make this run locally?

Using nginx, installed uwsgi but never used python as a backend before, and uwsgi docs seem written for people who already know what they're talking about ...

A Big Dummy's guide would be nice :-)

thanks, Ian

**Comment by iandoug** [comment]
Okay got something without using nginx:

~/1web/kle-render-2/kle_render-master $ uwsgi --http :9090 --plugins python37 --wsgi-file ./test.py 
*** Starting uWSGI 2.0.18 (64bit) on [Sat Sep 26 20:18:17 2020] ***
compiled with version: 9.2.0 on 25 September 2020 22:51:56
os: Linux-5.4.48-gentoo #2 SMP Wed Jul 8 19:16:35 SAST 2020
nodename: trooper
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/ian/1web/kle-render-2/kle_render-master
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 63820
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** RRDtool library available at 0x5597ff068b00 ***
uWSGI http bound on :9090 fd 4
spawned uWSGI http 1 (pid: 3769)
uwsgi socket 0 bound to TCP address 127.0.0.1:34833 (port auto-assigned) fd 3
Python version: 3.7.8 (default, Jul 20 2020, 08:47:44)  [GCC 9.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5597ff095b60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    from keyboard import Keyboard, deserialise
  File "./keyboard.py", line 3, in <module>
    from key import Key
  File "./key.py", line 3, in <module>
    from colormath import color_objects, color_conversions
ModuleNotFoundError: No module named 'colormath'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 3768, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 3768|app: -1|req: -1/1] 192.168.1.14 () {38 vars in 561 bytes} [Sat Sep 26 20:18:26 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Comment by CQCumbers** [comment]
Ideally, you should be able to run kle-render locally by running
```
pipenv install
pipenv run python app.py
```
That will run it with flask's development server instead of gunicorn, but the difference in concurrency shouldn't be an issue when running locally. I've also just updated the python version and some of the dependencies.
